### ISSUE TITLE
4.2 . It doesn't work?

### ISSUE THREAD

**Issue by kingz40o** [RedSiege/C2concealer#7]
Tried many times, but It didn't work. 
C2concealer  --variants 1 --hostname domain
[i] Building random C2 malleable profile with 1 variants.
[-] Attempted to create 10 profiles. All 10 failed c2lint check.
[i] If you selected a large amount of variants, please retry again.
[x] Exiting program.

**Comment by M4tszu** [comment]
?

**Comment by duckie37** [comment]
You find a solution to t his problem?
